RxDB Refactor
Cardano-Forge/MetaDraft pull request #61
Opened 2024-09-17 18:55 UTC by JFKFred

* Refactor the RxDB structure.
* Consolidate from 5 collections to 3 collections.
* Utilize database functionality instead of relying on local storage.
* Remove unnecessary hooks resulting from outdated and inefficient structuring.
* Status is now directly linked with the asset

**Database structure**
* MetadataCollection: { assetName, metadata, status }
* ValidationsCollection: { assetName, validation }
* ProjectCollection: { name, nfts, unchecked, errorFlagged, errorDetected, valids }

2024-09-17 20:05 UTC, pChausseC requested changes

2024-09-17 20:05 UTC, pChausseC commented on client/next-env.d.ts
> +// see https://nextjs.org/docs/app/building-your-application/configuring/typescript for more information.
this file should not be edited?

2024-09-17 20:05 UTC, pChausseC commented on client/src/providers/rxdb.provider.tsx
> +    reinitializeRxDB().catch(console.error);
db gets removed and re initialized on every page load (im not sure thats efficient)

2024-09-17 20:09 UTC, pChausseC requested changes

2024-09-17 20:09 UTC, pChausseC commented on client/src/providers/rxdb.provider.tsx
> +    reinitializeRxDB().catch(console.error);
`reinitializeRxDB` removes the db, but the db should already have been removed by the clean up function of the useEffect

2024-09-18 00:43 UTC, JFKFred commented on client/next-env.d.ts
> +// see https://nextjs.org/docs/app/building-your-application/configuring/typescript for more information.
i've run npm update, this might be why this have change ?

2024-09-18 13:34 UTC, pChausseC approved these changes

2024-09-18 13:34 UTC, merged